### ISSUE TITLE
remove .class files from being tracked by git

### ISSUE THREAD

**Issue by humbledshuttler** [katsun14/codeu-team18#16]
currently, we have added "target" directory in gitignore files so that the class files generated are not being tracked by git. Imagine we have have an actual directory named "target" which we want git to track, git won't be able to track it.
A general rule of thumb for gitignore is to add the file extensions that we want to ignore.
There are multiple other file types that we would not want git to track.

Let's use this java gitignore for now
https://github.com/github/gitignore/blob/master/Java.gitignore

**Comment by marcusblake** [comment]
Resolved with PR #25
